# AnthosCLI requires a nodepool object to describe the nodepool.
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: MANAGEMENT-NAME-pool # kpt-set: ${name}-pool
spec:
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 2
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    machineType: e2-standard-2 # changed from n1 to e2 for cost savings
    preemptible: false
    oauthScopes:
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/trace.append
    metadata:
      disable-legacy-endpoints: "true"
    workloadMetadataConfig:
      mode: GKE_METADATA
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: MANAGEMENT-NAME # kpt-set: ${name}
